obj-$(CONFIG_SENSORS_SSC)		+= sensors_ssc.o
obj-$(CONFIG_SENSORS)			+= sensors_core.o

# grip sensor
obj-$(CONFIG_SENSORS_A96T3X6)		+= a96t3x6.o
obj-$(CONFIG_SENSORS_SX9320)		+= sx9320.o
obj-$(CONFIG_SENSORS_SX9330)		+= sx9330.o
obj-$(CONFIG_SENSORS_SX9330_SUB)	+= sx9330_sub.o
obj-$(CONFIG_SENSORS_SX9330_SUB2)	+= sx9330_sub2.o
obj-$(CONFIG_SENSORS_SX9330_WIFI)	+= sx9330_wifi.o
