dtbo-$(CONFIG_SEC_BEYOND0QLTE_PROJECT) = sm8150-sec-beyond0qlte-overlay-r07.dtbo \
			sm8150-sec-beyond0qlte-overlay-r08.dtbo \
			sm8150-sec-beyond0qlte-overlay-r09.dtbo	\
			sm8150-sec-beyond0qlte-overlay-r12.dtbo	\
			sm8150-sec-beyond0qlte-overlay-r13.dtbo	\
			sm8150-sec-beyond0qlte-overlay-r14.dtbo	\
			sm8150-sec-beyond0qlte-overlay-r16.dtbo	\
			sm8150-sec-beyond0qlte-overlay-r17.dtbo
dtbo-$(CONFIG_SEC_BEYOND1QLTE_PROJECT) = sm8150-sec-beyond1qlte-overlay-r07.dtbo \
			sm8150-sec-beyond1qlte-overlay-r08.dtbo \
			sm8150-sec-beyond1qlte-overlay-r09.dtbo \
			sm8150-sec-beyond1qlte-overlay-r11.dtbo	\
			sm8150-sec-beyond1qlte-overlay-r12.dtbo	\
			sm8150-sec-beyond1qlte-overlay-r13.dtbo	\
			sm8150-sec-beyond1qlte-overlay-r14.dtbo	\
			sm8150-sec-beyond1qlte-overlay-r16.dtbo	\
			sm8150-sec-beyond1qlte-overlay-r17.dtbo
dtbo-$(CONFIG_SEC_BEYOND2QLTE_PROJECT) = sm8150-sec-beyond2qlte-overlay-r07.dtbo \
			sm8150-sec-beyond2qlte-overlay-r08.dtbo \
			sm8150-sec-beyond2qlte-overlay-r09.dtbo \
			sm8150-sec-beyond2qlte-overlay-r11.dtbo	\
			sm8150-sec-beyond2qlte-overlay-r12.dtbo	\
			sm8150-sec-beyond2qlte-overlay-r13.dtbo	\
			sm8150-sec-beyond2qlte-overlay-r14.dtbo	\
			sm8150-sec-beyond2qlte-overlay-r16.dtbo	\
			sm8150-sec-beyond2qlte-overlay-r17.dtbo
dtbo-$(CONFIG_SEC_WINNERLTE_PROJECT) = sm8150-sec-winnerlte-overlay-r04.dtbo	\
					sm8150-sec-winnerlte-overlay-r06.dtbo	\
					sm8150-sec-winnerlte-overlay-r08.dtbo	\
					sm8150-sec-winnerlte-overlay-r09.dtbo   \
					sm8150-sec-winnerlte-overlay-r11.dtbo   \
					sm8150-sec-winnerlte-overlay-r12.dtbo	\
					sm8150-sec-winnerlte-overlay-r15.dtbo
dtbo-$(CONFIG_SEC_WINNERX_PROJECT) = sm8150-sec-winnerx-overlay-r00.dtbo	\
					sm8150-sec-winnerx-overlay-r01.dtbo	\
					sm8150-sec-winnerx-overlay-r02.dtbo	\
					sm8150-sec-winnerx-overlay-r03.dtbo	\
					sm8150-sec-winnerx-overlay-r04.dtbo	\
					sm8150-sec-winnerx-overlay-r05.dtbo	\
					sm8150-sec-winnerx-overlay-r06.dtbo	\
					sm8150-sec-winnerx-overlay-r07.dtbo
dtbo-$(CONFIG_SEC_BOLTQ5G_PROJECT) = sm8150-sec-boltq5g-overlay-r04.dtbo	\
					sm8150-sec-boltq5g-overlay-r05.dtbo	\
					sm8150-sec-boltq5g-overlay-r07.dtbo	\
					sm8150-sec-boltq5g-overlay-r08.dtbo
dtbo-$(CONFIG_SEC_BEYONDXQ_PROJECT) = sm8150-sec-beyondxq-overlay-r04.dtbo	\
					sm8150-sec-beyondxq-overlay-r05.dtbo	\
					sm8150-sec-beyondxq-overlay-r09.dtbo	\
					sm8150-sec-beyondxq-overlay-r10.dtbo	\
					sm8150-sec-beyondxq-overlay-r12.dtbo	\
					sm8150-sec-beyondxq-overlay-r14.dtbo
dtbo-$(CONFIG_SEC_D2Q_PROJECT) = sm8150-sec-d2q-overlay-r00.dtbo	\
					sm8150-sec-d2q-overlay-r01.dtbo	\
					sm8150-sec-d2q-overlay-r02.dtbo	\
					sm8150-sec-d2q-overlay-r03.dtbo	\
					sm8150-sec-d2q-overlay-r04.dtbo
dtbo-$(CONFIG_SEC_GTS5L_PROJECT) = sm8150-sec-gts5l-overlay-r00.dtbo	\
					sm8150-sec-gts5l-overlay-r01.dtbo	\
					sm8150-sec-gts5l-overlay-r02.dtbo
dtbo-$(CONFIG_SEC_D1XQ_PROJECT) = sm8150-sec-d1xq-overlay-r00.dtbo	\
					sm8150-sec-d1xq-overlay-r03.dtbo
dtbo-$(CONFIG_SEC_D2XQ_PROJECT) = sm8150-sec-d2xq-overlay-r00.dtbo		\
					sm8150-sec-d2xq-overlay-r01.dtbo	\
					sm8150-sec-d2xq-overlay-r02.dtbo	\
					sm8150-sec-d2xq-overlay-r03.dtbo	\
					sm8150-sec-d2xq-overlay-r04.dtbo

ifeq ($(filter y,$(CONFIG_MACH_BEYOND1QLTE_JPN_DCM) $(CONFIG_MACH_BEYOND1QLTE_JPN_KDI)),y)
dtbo-y = sm8150-sec-beyond1qlte-jpn-overlay-r08.dtbo \
	sm8150-sec-beyond1qlte-jpn-overlay-r13.dtbo \
	sm8150-sec-beyond1qlte-jpn-overlay-r16.dtbo \
	sm8150-sec-beyond1qlte-jpn-overlay-r17.dtbo
endif

ifeq ($(filter y,$(CONFIG_MACH_BEYOND2QLTE_JPN_DCM) $(CONFIG_MACH_BEYOND2QLTE_JPN_KDI)),y)
dtbo-y = sm8150-sec-beyond2qlte-jpn-overlay-r09.dtbo \
	sm8150-sec-beyond2qlte-jpn-overlay-r13.dtbo \
	sm8150-sec-beyond2qlte-jpn-overlay-r16.dtbo \
	sm8150-sec-beyond2qlte-jpn-overlay-r17.dtbo
endif

ifeq ($(filter y,$(CONFIG_MACH_BEYOND0QLTE_CHNZC) $(CONFIG_MACH_BEYOND0QLTE_CHNZM) $(CONFIG_MACH_BEYOND0QLTE_CHN_LDU)),y)
dtbo-y = sm8150-sec-beyond0qlte-overlay-r07.dtbo \
	sm8150-sec-beyond0qlte-overlay-r08.dtbo \
	sm8150-sec-beyond0qlte-overlay-r09.dtbo	\
	sm8150-sec-beyond0qlte-chn-overlay-r12.dtbo \
	sm8150-sec-beyond0qlte-chn-overlay-r13.dtbo \
	sm8150-sec-beyond0qlte-chn-overlay-r14.dtbo \
	sm8150-sec-beyond0qlte-chn-overlay-r16.dtbo \
	sm8150-sec-beyond0qlte-chn-overlay-r17.dtbo
endif

ifeq ($(filter y,$(CONFIG_MACH_BEYOND0QLTE_CHNZH)),y)
dtbo-y = sm8150-sec-beyond0qlte-chnhk-overlay-r07.dtbo \
	sm8150-sec-beyond0qlte-chnhk-overlay-r08.dtbo \
	sm8150-sec-beyond0qlte-chnhk-overlay-r09.dtbo \
	sm8150-sec-beyond0qlte-chnhk-overlay-r12.dtbo \
	sm8150-sec-beyond0qlte-chnhk-overlay-r13.dtbo \
	sm8150-sec-beyond0qlte-chnhk-overlay-r14.dtbo \
	sm8150-sec-beyond0qlte-chnhk-overlay-r16.dtbo \
	sm8150-sec-beyond0qlte-chnhk-overlay-r17.dtbo
endif

ifeq ($(filter y,$(CONFIG_MACH_BEYOND1QLTE_CHNZH)),y)
dtbo-y = sm8150-sec-beyond1qlte-chnhk-overlay-r07.dtbo \
	sm8150-sec-beyond1qlte-chnhk-overlay-r08.dtbo \
	sm8150-sec-beyond1qlte-chnhk-overlay-r09.dtbo \
	sm8150-sec-beyond1qlte-chnhk-overlay-r11.dtbo \
	sm8150-sec-beyond1qlte-chnhk-overlay-r12.dtbo \
	sm8150-sec-beyond1qlte-chnhk-overlay-r13.dtbo \
	sm8150-sec-beyond1qlte-chnhk-overlay-r14.dtbo \
	sm8150-sec-beyond1qlte-chnhk-overlay-r16.dtbo \
	sm8150-sec-beyond1qlte-chnhk-overlay-r17.dtbo
endif

ifeq ($(filter y,$(CONFIG_MACH_BEYOND2QLTE_CHNZH)),y)
dtbo-y = sm8150-sec-beyond2qlte-chnhk-overlay-r07.dtbo \
	sm8150-sec-beyond2qlte-chnhk-overlay-r08.dtbo \
	sm8150-sec-beyond2qlte-chnhk-overlay-r09.dtbo \
	sm8150-sec-beyond2qlte-chnhk-overlay-r11.dtbo \
	sm8150-sec-beyond2qlte-chnhk-overlay-r12.dtbo \
	sm8150-sec-beyond2qlte-chnhk-overlay-r13.dtbo \
	sm8150-sec-beyond2qlte-chnhk-overlay-r14.dtbo \
	sm8150-sec-beyond2qlte-chnhk-overlay-r16.dtbo \
	sm8150-sec-beyond2qlte-chnhk-overlay-r17.dtbo
endif

ifeq ($(filter y,$(CONFIG_MACH_D2Q_CHNZC) $(CONFIG_MACH_D2Q_CHNZH) $(CONFIG_MACH_D2Q_CHNZM)),y)
dtbo-y = sm8150-sec-d2q-chn-overlay-r01.dtbo \
	sm8150-sec-d2q-chn-overlay-r02.dtbo \
	sm8150-sec-d2q-chn-overlay-r03.dtbo \
	sm8150-sec-d2q-chn-overlay-r04.dtbo
endif

ifeq ($(filter y,$(CONFIG_MACH_D2Q_JPN_DCM) $(CONFIG_MACH_D2Q_JPN_KDI) $(CONFIG_MACH_D2Q_JPN_RKT)),y)
dtbo-y = sm8150-sec-d2q-jpn-overlay-r01.dtbo \
	sm8150-sec-d2q-jpn-overlay-r02.dtbo \
	sm8150-sec-d2q-jpn-overlay-r03.dtbo \
	sm8150-sec-d2q-jpn-overlay-r04.dtbo
endif

ifeq ($(filter y,$(CONFIG_MACH_BEYONDXQ_CHN_OPEN)),y)
dtbo-y = sm8150-sec-beyondxq-chn-overlay-r04.dtbo \
	sm8150-sec-beyondxq-chn-overlay-r05.dtbo \
	sm8150-sec-beyondxq-chn-overlay-r09.dtbo \
	sm8150-sec-beyondxq-chn-overlay-r10.dtbo \
	sm8150-sec-beyondxq-chn-overlay-r12.dtbo \
	sm8150-sec-beyondxq-chn-overlay-r14.dtbo
endif

ifeq ($(filter y,$(CONFIG_MACH_WINNERX_KOR_SINGLE)),y)
dtbo-y = sm8150-sec-winnerx-kor-overlay-r00.dtbo \
	sm8150-sec-winnerx-kor-overlay-r01.dtbo \
	sm8150-sec-winnerx-kor-overlay-r02.dtbo \
	sm8150-sec-winnerx-kor-overlay-r03.dtbo \
	sm8150-sec-winnerx-kor-overlay-r04.dtbo \
	sm8150-sec-winnerx-kor-overlay-r05.dtbo
endif

sm8150-sec-beyond0qlte-overlay-r07.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-overlay-r08.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-overlay-r09.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-overlay-r12.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-overlay-r13.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-overlay-r14.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-overlay-r16.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-overlay-r17.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chn-overlay-r12.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chn-overlay-r13.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chn-overlay-r14.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chn-overlay-r16.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chn-overlay-r17.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chnhk-overlay-r07.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chnhk-overlay-r08.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chnhk-overlay-r09.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chnhk-overlay-r12.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chnhk-overlay-r13.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chnhk-overlay-r14.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chnhk-overlay-r16.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond0qlte-chnhk-overlay-r17.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-overlay-r07.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-overlay-r08.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-overlay-r09.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-overlay-r11.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-overlay-r12.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-overlay-r13.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-overlay-r14.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-overlay-r16.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-overlay-r17.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-chnhk-overlay-r07.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-chnhk-overlay-r08.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-chnhk-overlay-r09.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-chnhk-overlay-r11.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-chnhk-overlay-r12.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-chnhk-overlay-r13.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-chnhk-overlay-r14.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-chnhk-overlay-r16.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-chnhk-overlay-r17.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-overlay-r07.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-overlay-r08.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-overlay-r09.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-overlay-r11.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-overlay-r12.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-overlay-r13.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-overlay-r14.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-overlay-r16.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-overlay-r17.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-jpn-overlay-r08.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-jpn-overlay-r13.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-jpn-overlay-r16.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond1qlte-jpn-overlay-r17.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-jpn-overlay-r09.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-jpn-overlay-r13.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-jpn-overlay-r16.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-jpn-overlay-r17.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-chnhk-overlay-r07.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-chnhk-overlay-r08.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-chnhk-overlay-r09.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-chnhk-overlay-r11.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-chnhk-overlay-r12.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-chnhk-overlay-r13.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-chnhk-overlay-r14.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-chnhk-overlay-r16.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyond2qlte-chnhk-overlay-r17.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r04.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r06.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r08.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r09.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r11.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r12.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r15.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r00.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r01.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r02.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r03.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r04.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r05.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r06.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r07.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r00.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r01.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r02.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r03.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r04.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r05.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-boltq5g-overlay-r04.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-boltq5g-overlay-r05.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-boltq5g-overlay-r07.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-boltq5g-overlay-r08.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-overlay-r04.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-overlay-r05.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-overlay-r09.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-overlay-r10.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-overlay-r12.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-overlay-r14.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-chn-overlay-r04.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-chn-overlay-r05.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-chn-overlay-r09.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-chn-overlay-r10.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-chn-overlay-r12.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-beyondxq-chn-overlay-r14.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d1xq-overlay-r00.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d1xq-overlay-r03.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2xq-overlay-r00.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2xq-overlay-r01.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2xq-overlay-r02.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2xq-overlay-r03.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2xq-overlay-r04.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-overlay-r00.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-overlay-r01.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-overlay-r02.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-overlay-r03.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-overlay-r04.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-chn-overlay-r01.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-chn-overlay-r02.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-chn-overlay-r03.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-chn-overlay-r04.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-jpn-overlay-r01.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-jpn-overlay-r02.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-jpn-overlay-r03.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-d2q-jpn-overlay-r04.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-gts5l-overlay-r00.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-gts5l-overlay-r01.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb
sm8150-sec-gts5l-overlay-r02.dtbo-base := ../qcom/sm8150.dtb ../qcom/sm8150-v2.dtb

ifeq ($(CONFIG_ARM64),y)
always          := $(dtb-y)
subdir-y        := $(dts-dirs)
else
targets += dtbs
targets += $(addprefix ../, $(dtb-y))

$(obj)/../%.dtb: $(src)/%.dts FORCE
        $(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/../,$(dtb-y))
endif
clean-files := *.dtb *.reverse.dts *.dtbo

